name: Deployment
on:
  push:
    branches:
    - develop

jobs:
  buildAndDeploy: 
    name: Build and Deploy Blog

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install packages
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install

    - name: Build Blog
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build

    - name: Deploy Blog
      uses: peaceiris/actions-gh-pages@v2.2.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
